fastlane_version "2.14.2"

default_platform :ios

platform :ios do

  desc "Create new screenshots for the App Store in all languages and device types"
  desc "Additionally, this will add device frames around the screenshots and add the correct titles"
  lane :screenshots do
    snapshot(scheme: "Volumio")
    frameit(white: true, path: './Screenshots')
  end

  error do |lane, exception|
  # This block is called, if there was an error running a specific lane.
  end

end

